version: 2.1

# Caching between jobs mmmmmm
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      #- run: mkdir -p workspace
      #- run: cd workspace
      - run: echo  "HELLLLLOOOOO WWWWOOOORRRRLLLLLLD" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: .
          # root: ~/
          # paths:
          #   - output.txt
      - run: cat output.txt
          # root: ~/.circleci
          # paths:
          #   - output.txt
          #- run: ~/.circle.ci/cat output.txt
          # at: ~/
          #root: ~/
          #paths:
          #  - output.txt
          #- run: cat ~/output.txt

workflows:
  default:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
          - save_hello_world_output

